# Generated by Django 5.1.2 on 2024-10-19 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_alter_vehiculo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('visualizar_catalogo', 'Puede visualizar Catálogo de Vehículos'), ('agregar_vehiculo', 'Puede agregar Vehículos')]},
        ),
    ]
